cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    queues:
      uri: http://localhost:4566
      toPreparation:
        name: opin-testing-queue

spring:
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://admin:admin@localhost:27017/order-system?authSource=admin

#actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always